(Draft) Testing a few backlogged Zero variants (+ a few others)
be5invis/Iosevka pull request #1734
Opened 2023-05-19 14:21 UTC by Logo121

Starting this because the major number is going to change anyway:
![image](https://github.com/be5invis/Iosevka/assets/21302803/572899ab-480d-4da6-bd8b-45b4468cbf85)

This covers the proposed zero variants suggested in:
* #1307:
  * Slash cutout with same slope as the default slashed 0 (https://github.com/be5invis/Iosevka/issues/1307#issue-1138378807)
  * Slash cutout with steeper slope (https://github.com/be5invis/Iosevka/issues/1307#issuecomment-1052195735)
  * Top-right cutout, like the license plate font (https://github.com/be5invis/Iosevka/issues/1307#issuecomment-1053588047)
  * Vertical cutout, like stencil font (https://github.com/be5invis/Iosevka/issues/1307#issuecomment-1553649962)
* #1509
  * Slash with steeper slope (from (0, 0) to (Width, top), I assume)
    * This is aligned with the steeper-slope cutout above
* #1678 
  * Broken vertical bar
  * Broken Slash, like Fixedsys, as I've mentioned and demonstrated (https://github.com/be5invis/Iosevka/issues/1678#issuecomment-1518214429)
    * The slope is aligned with that of Empty Set, because there would be very little remaining if the other slopes are used

Plus their respective Oval/onum forms. The config has also been modified to support the "broken" shapes.

This is just for testing now, and I don't think *all* of these (especially those raised by me) are to be added anyway. For this reason, I also didn't make the reversed slash equivalent, or edit the variant table. These are all encoded in the PUA (U+EF00...U+EF1B) for now.

This is how it looks like zoomed out: ![image](https://github.com/be5invis/Iosevka/assets/21302803/410d930c-a706-468f-b0fb-30e192b70b3b)

I'm putting this here to know what should be done next, in particular:
* Which to keep, or even what to add (e.g. reversed variants)
* What optimizations/fixes should be done
* How to order them with the existing zero variants

2023-05-19 18:48 UTC, wimstefan commented
Thank you so much for all the hard work you put into it!
It would be simply fantastic to see my cautious request being realized after such a long time 😃

2023-05-21 03:04 UTC, be5invis requested changes

2023-05-21 03:04 UTC, be5invis commented on font-src/glyphs/number/0.ptl
> +		flat Middle (top - O) [widths.center (Width * 0.125)]
Change the stroke width after (`widths.center`) to things like
`[Math.min (0.4 * CircleInnerWidth) [AdviceStroke 4]]`

2023-05-21 03:04 UTC, be5invis commented on font-src/glyphs/number/0.ptl
> +		flat 0 0 [widths.center (top * 0.125)]
Change the stroke width after (`widths.center`) to things like
`[Math.min (0.4 * CircleInnerWidth) (top * 0.15) [AdviceStroke 3]]`

Adjust the parameters to make the SW being proper under all the weights.

2023-05-21 03:04 UTC, be5invis commented on font-src/glyphs/number/0.ptl
> +		flat 0 (top * (1 - 0.77)) [widths.center (top * 0.125)]
Change the stroke width after (`widths.center`) to things like
`[Math.min (0.4 * CircleInnerWidth) (top * 0.15) [AdviceStroke 3]]`

Adjust the parameters to make the SW being proper under all the weights.

2023-05-21 03:04 UTC, be5invis commented on font-src/glyphs/number/0.ptl
> +		flat Middle (top - O) [widths.center (Width * 0.125)]
Adjust the parameters to make the SW being proper under all the weights.

2023-05-21 03:06 UTC, be5invis commented
And well, you can keep all the variants (modify `variants.toml` to add them under `[prime.zero.variants]`). Since V23 will be a major version change you can freely reorder the variants' rank.

2023-05-21 05:06 UTC, Lieutenant-L-T-Smash commented
+1 to the steeper slash. If anything makes it through to final, it must be that one. Looking at this chart and being able to compare, it's surprising even to me how much difference that makes in making it distinguishable from the 8 under astigmatic vision.

The vertical cutout just looks like a pair of parentheses to me.

2023-05-21 18:07 UTC, Logo121 commented
Ok, I tried making the gap vary a bit more, though if I just use AdviceStroke without a lower bound, the gap will be almost non-existent in Thin (and Extralight to some extent): ![image](https://github.com/be5invis/Iosevka/assets/21302803/3c51478d-bdd1-47ed-b65e-cab41fda0060)

I tried to keep the effect that the gaps are still discernible when zoomed out (or at around 8pt), at least for me:
![image](https://github.com/be5invis/Iosevka/assets/21302803/9bd68194-703a-40b6-bf71-472eb5d51b97)![image](https://github.com/be5invis/Iosevka/assets/21302803/71479211-265d-4eba-8e8c-92c6635ec15c)

And this is what it looks like up close (at around 24pt):
![image](https://github.com/be5invis/Iosevka/assets/21302803/5e4f85d2-76d8-4751-bd12-9af9bdff5996) ![image](https://github.com/be5invis/Iosevka/assets/21302803/aa64ed17-8ecd-44e3-a6e9-74289883f197)

Not sure if it's better now.

2023-05-21 19:32 UTC, merged