Breakup `R` motion-serifed variant into multiple variants, also add them for Cyrillic Ya
be5invis/Iosevka pull request #1988
Opened 2023-09-08 18:42 UTC by jmcwilliams403

`R₹ꝚꝛKkκКкЯя`
`ss15`:
![image](https://github.com/be5invis/Iosevka/assets/37010132/a638257b-e9af-4a77-ab11-ad7613c22fc3)
Compared to IBM Plex Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/0f1ee4e7-c717-4f6b-a177-8ce464782171)
`ss17`:
![image](https://github.com/be5invis/Iosevka/assets/37010132/416e69c9-6d91-4d32-bdd9-6be1c9af4ac5)
Compared to Recursive Sans Mono Linear:
![image](https://github.com/be5invis/Iosevka/assets/37010132/a9710ead-f911-45cd-8bb9-07a4f2bdd81c)
![image](https://github.com/be5invis/Iosevka/assets/37010132/cd4bd309-ae96-4cd5-a159-9078597c675a)

2023-09-08 22:08 UTC, be5invis requested changes

2023-09-08 22:08 UTC, be5invis commented on changes/26.3.3.md
>  * \[**Breaking**\] Change of variant names:
If it is breaking, then make the version number 27.0.0, and remove all lines in `variants.toml` containing `nonBreakingVariantAdditionPriority` or `nonBreakingTagForNewVariantSelector`.

2023-09-08 22:08 UTC, be5invis commented on changes/26.3.3.md
>  * \[**Breaking**\] Change of variant names:
In addition, _measure_ the impact of glyph quantity of your change.

2023-09-09 15:11 UTC, jmcwilliams403 commented
I can't currently change the version name of the \.md file without breaking parity with the dev branch as of 366f377

2023-09-09 15:19 UTC, jmcwilliams403 commented
Also I chose the breaking option because I already made a breaking change with #1986 and I figured it would be more effort than it's worth to turn everything so far into a non-breaking change at this point.

2023-09-09 16:36 UTC, jmcwilliams403 commented
Nevermind I just realized that 26.3.3 is already out. I'll start this commit over later without breaking anything.

2023-09-09 20:38 UTC, be5invis commented
@jmcwilliams403 I'd like to merge this now as I decided to create version 27.0.
No need for a new PR -- I will fix everything later.

2023-09-09 20:38 UTC, merged