Add various dingbats and punctuation characters.
be5invis/Iosevka pull request #2219
Opened 2024-03-04 15:10 UTC by jmcwilliams403

* For the 3D arrows, I've seen them in use as decorative bullets in Powerpoint presentations. They are handled similarly to other outlined half-filled shapes.
* For the omission brackets, it completes the set with raised square for biblical transcription.
  * the paraphrase brackets are used for different purposes but they look identical in the Unicode charts apart from being subscript.
* For the circled 18 with overlaid backslash, it happens to be one of two characters described as additional enclosed alphanumeric characters, the other of which (keycap 10) is not added here because it involves a keycap enclosure, whose glyph exists in Unicode as a combining enclosing character that we do not yet support.
  * here I have made it narrow by default unless the font is made quasi-proportional, as I feel it is more appropriate to treat it specially since it's named specially in Unicode ("no one under eighteen symbol") and it implies a restriction of access to a piece of media even if not necessarily copyright.
* Black heart is just the generic form of heavy black heart; Heavy black heart has an emoji form that is equivalent to a red heart, which is obviously out of scope. Under black and white text, both glyphs may look identical.
  * Maybe we can later distinguish them by making the heavy one fatter like how they are in the Unicode charts.
* The last one is just a raised left square bracket for the Unicode 16 proposed characters. A right square bracket is not proposed.
```
➢➣➤
⸋⸌x⸍⸜x⸝
🔞🖤
x🯌⁽
```
![image](https://github.com/be5invis/Iosevka/assets/37010132/1d7b0962-0a8b-4395-bf97-3af651ca8fa2)

2024-03-04 18:40 UTC, be5invis requested changes

2024-03-04 18:40 UTC, be5invis commented on packages/font-glyphs/src/auto-build/composite.ptl
> +	do "Double-digit backslash-circled"
Consider remove.
If we are not adding keycaps then we should remove the circled 18 with overlaid backslash too.
(Actually, I do NOT want to add ANY MORE new Emoji into Iosevka.)

2024-03-04 19:04 UTC, merged

2024-03-08 07:55 UTC, Logo121 commented
@jmcwilliams403 Are you sure about `🯌` being just a superscript `[`? The [alpha name list](https://www.unicode.org/Public/draft/UCD/ucd/NamesList.txt) does not mention it being a superscript (unlike `⁽` and others), and FairfaxHD makes it smaller:
![image](https://github.com/be5invis/Iosevka/assets/21302803/a4db85b3-5089-405b-9605-2ab83859d9c0)

2024-03-08 12:41 UTC, jmcwilliams403 commented
> @jmcwilliams403 Are you sure about `🯌` being just a superscript `[`? The [alpha name list](https://www.unicode.org/Public/draft/UCD/ucd/NamesList.txt) does not mention it being a superscript (unlike `⁽` and others), and FairfaxHD makes it smaller:

Well the name says "small" so it could stand to be changed if you want.

2024-03-08 14:57 UTC, jmcwilliams403 commented
@Logo121 fixed in #2222 :
`x🯌ˣ⁽ᴴ`
![image](https://github.com/be5invis/Iosevka/assets/37010132/4d8f882f-919d-4b0d-a2cc-9be33eb53485)