Harmonize glyphs/variants of several non-slavic Cyrillic letters.
be5invis/Iosevka pull request #2285
Opened 2024-04-09 17:44 UTC by jmcwilliams403

Cyrillic Letters with descenders:
`ЗзҘҙСсҪҫҼҽҾҿ`
(Not shown is Latin Ç/ç which is unchanged).
before:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ae0f6798-c202-4e92-8ee5-2449a82d66a7)
after:
(existing accepted style seen in some fonts as well as Wikipedia, which distinguishes them from a simple cedilla composition or straight bar down)
![image](https://github.com/be5invis/Iosevka/assets/37010132/92815752-32a7-4bba-86d6-82a6de47fb9f)
Schwa top hook behavior:
`ОоӨөЭэӘә`
(not shown is real turned e which is unchanged).
Upright:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5d7dc112-07d5-4b08-be47-68d5d0f692d6)
Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/d178ea68-642b-4686-8cf1-7fd95d90db5d)
Compared to slab:
Upright:
![image](https://github.com/be5invis/Iosevka/assets/37010132/9cfc1217-6cc1-4a3d-8162-f774ba6eee0d)
Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/0b7bad26-acda-4f6d-9af0-b84341fa7081)
Cyrillic Straight U behavior:
All Capital U variants:
`УЎҮҰ`
![image](https://github.com/be5invis/Iosevka/assets/37010132/1078b8be-61eb-421b-a41d-e9b610bf2d66)
All Lower U variants:
`уўүұ`
![image](https://github.com/be5invis/Iosevka/assets/37010132/7f098a60-39e1-49f0-af8b-3d051995681f)

2024-04-09 20:14 UTC, be5invis commented
I don't think ogoneks are widely accepted for Ҙҙ Ҫҫ Ҿҿ. Let us just follow the Unicode chart.

2024-04-09 20:17 UTC, be5invis requested changes

2024-04-09 20:17 UTC, be5invis commented on packages/font-glyphs/src/letter/latin/c.ptl
> +	derive-composites 'cyrl/The' 0x4AA 'cyrl/Es' 'ogonekBelow'
Please revert to use Cedilla. The Es-Ogonek form is only considered as "Occasionally used" per Wikipedia.

2024-04-09 20:17 UTC, be5invis commented on packages/font-glyphs/src/letter/greek/lower-epsilon.ptl
> +	derive-composites 'cyrl/Dhe' 0x498 'cyrl/Ze' 'ogonekBelow'
Please revert to use Cedilla to be conformal to Unicode chart.

2024-04-09 20:17 UTC, be5invis commented on packages/font-glyphs/src/letter/latin/lower-e.ptl
> +	define [AbkCheShape] : with-params [Body df top tailSlab] : glyph-proc
Please revert and use straight descender, to be conformal to Unicode chart.

2024-04-09 20:44 UTC, berrymot commented
the unicode charts do not prescribe glyphs

2024-04-10 13:09 UTC, jmcwilliams403 commented
I kept some of the code cleanup and the `cyrl/Dhe` rename but otherwise the descender glyphs are back to normal.

2024-04-10 18:21 UTC, be5invis approved these changes

2024-04-10 18:21 UTC, merged