Random collection of geometric glyphs
be5invis/Iosevka pull request #2497
Opened 2024-09-10 15:02 UTC by Logo121

None of these have real justification, just being close enough to existing glyphs.

<details><summary>Preview</summary>

`𝍠𝍡𝍢𝍣𝍤𝍥𝍦𝍧𝍨𝍩𝍪𝍫𝍬𝍭𝍮𝍯𝍰𝍱𝍲𝍳𝍴𝍵𝍶𝍷𝍸`
![Pasted image 20240910225626](https://github.com/user-attachments/assets/1e33f265-01b0-425b-b557-a09d790e3a7e)
In QP:
![Pasted image 20240910225643](https://github.com/user-attachments/assets/19987c07-2623-40ef-a209-96e4b393e6d9)

`⎄ ⭘⭙ ⛚⛋⛝⛞⹙⹚⹛⹜`
![Pasted image 20240910225713](https://github.com/user-attachments/assets/c963c936-4019-474f-9e44-2503cc16e739)
</details>

---

Covered Range:
- `U+1D360` - `U+1D376` (The rest of counting rod numerals block)
	- These are straightforward to make. Mostly extension of the existing tally mark code.
	- For the Counting Rod numerals, the strokes were scaled to be the same across all the ones and tens digits.
		- this made the Heavy monospace strokes too thin, so the horizontal strokes are modified to use a different sw.
- `U+2E59` - `U+2E5C` (Half parenthesis)
	- Copied code for half square brackets.
- `U+2384`, `U+26DA`, `U+26CB`, `U+26DD`, `U+26DE`
	- Random collection of geometric symbols that can be done with some simple composition.
- `U+2B59` (Heavy Circled Saltire)
	- Implemented as "poweroff" with saltire for consistency. Ideally both should be actual circles, but Heavy Circle is also used as poweroff symbol, which Iosevka currently implements to be a standard "ring" instead.
	- If other symbols from the same set like `⭗` (or even `⭖`) are to be implemented, they may need to follow this as well, unless something is done with the power symbols.

2024-09-10 15:09 UTC, jmcwilliams403 commented
Composition symbol (`⎄`) should always have the circle centered on the middle of the stroke of the edge of the square

2024-09-10 21:21 UTC, be5invis requested changes

2024-09-10 21:21 UTC, be5invis commented on packages/font-glyphs/src/symbol/counting-rod.ptl
> +	do "Tally Mark Ideographic"
Please remove. Iosevka is **not** a CJK typeface.

2024-09-10 21:23 UTC, be5invis requested changes

2024-09-10 21:23 UTC, be5invis commented on changes/31.6.2.md
> +* Add Characters:
Please consider bump the version of the change file to 31.7.0 as there's new features added.

2024-09-10 22:48 UTC, Logo121 commented
I'll deal with the changes tomorrow, marking as draft now

> Ideographic tally marks should be forced to a wide monospace (technically duospace?) square grid.

Wasn't aware of this requirement. It _is_ marked as "Wide" in Unicode, but there are many other "Wide" glyphs that are implemented as Mosaic (both widths), or even just narrow width.

At least JuliaMono implements the whole Counting Rod block as halfwidth too, but again it's JuliaMono.

> Please remove. Iosevka is **not** a CJK typeface.

Again I'm not so sure where's the line between "CJK" and "non-CJK" for symbols like these. For me it's just another tally system, which some non-CJK but pan-Unicode font supports because they are straightforward enough to make.

But just to be clear, do I remove the Ideograph Tallies only, or the other counting rods as well? Since their primary usage is in CJKV anyway.

2024-09-11 00:29 UTC, be5invis commented
The ideographic tally marks are partial writing of the "正" (U+6B63) character.
See https://www.unicode.org/L2/L2016/16046-ideo-tally-marks.pdf.

> But just to be clear, do I remove the Ideograph Tallies only, or the other counting rods as well? Since their primary usage is in CJKV anyway.

Remove the five ideographic tally marks only.

2024-09-11 16:42 UTC, Logo121 commented
Ok the current revision should have the widths fixed now (the unspaced Tens glyphs looks like that on my computer, probably Noto. Nishikiteki also has this form iirc). The other changes (including the deletion) are applied accordingly.

But for monospaced version, I'm not sure what you mean by "Default them to Wide". Since they are not mosaics at the moment (following the Tally Marks), only Narrow version exists.  
So do I:
- Make the Counting Rod mosaics (but keep the behavior of Tally Marks as is);
- Make the whole block mosaic, but somehow keep the Tally Mark One width for QP only (e.g. making them not Mosaics in QP); or
- Make the Counting Rod Wide only (like the long arrows) and have them removed in Monospace-only versions?

---

> The ideographic tally marks are partial writing of the "正" (U+6B63) character.
> See https://www.unicode.org/L2/L2016/16046-ideo-tally-marks.pdf.

This part I know, but my point is when other font creators make glyphs for this block (which admittedly there are probably less than 10 fonts supporting the block completely), I doubt most would even care about those being CJK or not because they are easily abstractable as just "5 orthogonal lines in a certain pattern".

I'm also not quite aware of any technicalities or mechanisms that would make this font "CJK font" just because of the inclusion of these glyphs, unlike the squared units last time (#1651) or the ideographic space. Unless the "Ideographic" in its name is somehow triggering something?

2024-09-11 16:57 UTC, jmcwilliams403 commented
> I'm also not quite aware of any technicalities or mechanisms that would make this font "CJK font" just because of the inclusion of these glyphs, unlike the squared units last time (ref) or the ideographic space. Unless the "Ideographic" in its name is somehow triggering something?

Belleve has said in the past that inclusion of certain characters whose primary script is officially specified as something ideographic causes certain applications to treat the whole font as a CJK font, and if that were the user's actual intention then it would be better to use [Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic) instead, which includes Iosevka as a subset.

2024-09-12 01:03 UTC, be5invis commented
> Default them to Wide

nvm I will implement this. LGTM now.

2024-09-12 01:06 UTC, merged