Draft: Add new diversity classification `diversityMM` for composite characters and similar.
be5invis/Iosevka pull request #2611
Opened 2024-12-08 14:41 UTC by jmcwilliams403

This effectively makes composite characters, including `W`/`w`/`m`, perfectly proportional with the characters their individual components are derived from. This does _not_ universally apply to all characters, as many characters already look proportional as-is.
```
AꜲÆꜴꜶBCDÐEƎƏFGHIJKLMN
ᴬ𐞀ᴭᴭᴭᴮꟲᴰᶞᴱᴲᴲꟳᴳᴴᴵᴶᴷᴸᴹᴺ
ᴀᴁᴁᴁᴁʙᴄᴅᴆᴇⱻⱻꜰɢʜɪᴊᴋʟᴍɴ
aꜳæꜵꜷbcdðeɘəfghijklmn
ᵃ𐞃𐞃𐞃𐞃ᵇᶜᵈᶞᵉ𐞎ᵊᶠᵍʰⁱʲᵏˡᵐⁿ
OŒꝎPQRSSTUƜƜƜVWXYZÞẞ
ᴏɶɶᴘꞯʀꜱꜱᴛᴜꟺꟺꟺᴠᴡxʏᴢ
ᴼ𐞣𐞣ᴾꟴᴿˢˢᵀᵁᵂᵂᵂⱽᵂˣ𐞲ᶻ
oœꝏpqrſstuᵫꭣɯvwxyzþß
ᵒꟹꟹᵖ𐞥ʳˢˢᵗᵘᵚᵚᵚᵛʷˣʸᶻ
```
Aile Latin before:
![image](https://github.com/user-attachments/assets/e5421204-f652-4123-bed4-d214c7191563)
Aile Latin After:
![image](https://github.com/user-attachments/assets/e58906bf-51c2-4c04-a9cd-c45a8eb16752)
Etoile Latin Before:
![image](https://github.com/user-attachments/assets/b995e678-3ddb-451a-86d3-209a67477fba)
Etoile Latin After:
![image](https://github.com/user-attachments/assets/13c0f7cc-9dca-4043-82be-3b5b5ad55cd7)

```
ΑΒΒΓϜΔ∇ΕΕΖΗΘϴΙΚΚΛΜΝ
αβϐγϝδ∂εϵζηθϑικϰλμν
ΞΟΠΠΡΡΣΣΤΥϒΦΦΧΨΩ
ξοπϖρϱςστυυφϕχψω
```
Aile Greek Before:
![image](https://github.com/user-attachments/assets/070e0d89-779b-4814-a5f6-d8c6793eba36)
Aile Greek After:
![image](https://github.com/user-attachments/assets/034dcdab-4e92-4d26-80ef-04b2055c1bcf)
Etoile Greek Before:
![image](https://github.com/user-attachments/assets/f21dde2a-ae4b-438a-bd61-7ccc4af7274e)
Etoile Greek After:
![image](https://github.com/user-attachments/assets/e3036e83-33bd-4442-9284-7b101344bf94)
```
АꙖБВГЃҐҔДꙢꚈЂԂЕЀЁҼҾѤЄѤ
аꙗбвгѓґҕдꙣꚉђԃеѐёҽҿꭡєѥ
𞀰𞀰𞀱𞀲𞀳𞀳́𞀳𞀳𞀴𞀴𞁊𞀴𞀴𞀵𞀵̀𞀵̈𞀵𞀵𞀵𞀵𞀵
ЖԪꚄЗҘԄЅИІЇЍЙЈҠКЌӃЛЉԈꙤԠ
жԫꚅзҙԅѕиіїѝйјҡкќӄлљԉꙥԡ
𞀶𞀶𞀶𞀷𞀷𞀷𞀷𞀸𞁌𞁌̈𞀸̀𞀸̆𞁍𞀹𞀹́𞀹𞀹𞀺𞀺𞀺𞀺𞀺
МꙦНЊԊҤԢОЮꙔППҦРСҪТᲉԎꚊЋ
мꙧнњԋҥԣоюꙕпꭠҧрсҫтᲊԏꚋћ
𞀻𞀻ᵸᵸᵸᵸᵸ𞀼𞁉𞁉𞀽𞀽𞀽𞀾𞀿𞁫𞁀𞁀𞁀𞁀𞁀
УЎФХӼЦҴЧꚒЏШЩꙐЪЫЬѢꙒЭЯ
уўфхӽцҵчꚓџшщꙑъыьѣꙓэя
𞁁𞁁̆𞁂𞁃𞁃𞁄𞁄𞁅𞁅𞁅𞁆𞁆𞁬ꚜ𞁇ꚝꚝ𞁇𞁈
```
Aile Cyrillic Before:
![image](https://github.com/user-attachments/assets/55673779-9afc-4685-8433-868d11792ffa)
Aile Cyrillic After:
![image](https://github.com/user-attachments/assets/134ecd38-db5d-466b-a723-4fb1e9c630bc)
Etoile Cyrillic Before:
![image](https://github.com/user-attachments/assets/71ad5a0c-335b-41e4-8b86-ec1903095dfc)
Etoile Cyrillic After:
![image](https://github.com/user-attachments/assets/5d77f8d3-429c-4fe4-a2ed-72a43ddc4437)

2024-12-08 20:29 UTC, be5invis commented
Looks nice.

2024-12-08 20:37 UTC, be5invis requested changes
Please attach before/after samples of the text in **sentences**.

2024-12-08 20:37 UTC, be5invis commented on packages/font-glyphs/src/letter/latin/upper-h.ptl
> +			local df : include : DivFrame para.diversityMM 3
Maybe for lowercase Komi letters we could still use `diversityM`. They are slightly too wide and the ail is not a "full" letter.

2024-12-08 20:37 UTC, be5invis commented on packages/font-glyphs/src/letter/greek/lower-omega.ptl
> +		local df : include : DivFrame para.diversityMM 3
I think lower omega aligns better with `m/w` rather than `MM`.

2024-12-08 20:37 UTC, be5invis commented on packages/font-glyphs/src/letter/latin/upper-h.ptl
> +			local df : include : DivFrame para.diversityMM 3
This change is optional though.

2024-12-08 20:42 UTC, be5invis requested changes

2024-12-08 20:42 UTC, be5invis commented on packages/font-glyphs/src/letter/cyrillic/zhe.ptl
> +			local df : include : DivFrame para.diversityMM 3
Lowercase zhe looks too wide in your samples.

2024-12-08 20:42 UTC, be5invis commented on packages/font-glyphs/src/letter/greek/phi.ptl
> +			local df : include : DivFrame para.diversityMM 3
Lower case Ef looks too wide in your samples.

2024-12-08 20:42 UTC, be5invis commented on packages/font-glyphs/src/letter/cyrillic/zhe.ptl
> +			local df : include : DivFrame para.diversityMM 3
Perhaps many more lowercase Cyrillic letters using MM metrics could be reduced back to M metrics, like Nje, Lje, etc.

2024-12-08 20:45 UTC, jmcwilliams403 commented
Regarding ef and images of sentences:
![image](https://github.com/user-attachments/assets/f7a1c468-696b-42fe-b113-c807182c8916)

2024-12-08 20:46 UTC, jmcwilliams403 commented
![image](https://github.com/user-attachments/assets/8f45e2b8-3a34-468d-9eff-2be129d33997)

2024-12-08 20:57 UTC, jmcwilliams403 commented
Showing zhe:
![image](https://github.com/user-attachments/assets/15ed27c7-7419-4ffb-981d-212ba79d255e)

2024-12-08 21:00 UTC, jmcwilliams403 commented
I will work on your requested changes later.

2024-12-09 13:20 UTC, jmcwilliams403 commented
Changes to Greek are reverted. Rather than taking more screenshots, I removed the Greek section from the body of my PR.

2024-12-09 14:34 UTC, jmcwilliams403 commented on packages/font-glyphs/src/letter/greek/phi.ptl
> +			local df : include : DivFrame para.diversityMM 3
I think it's just that being next to non-cursive `у`/`х` is unflattering.

2024-12-09 16:49 UTC, jmcwilliams403 commented on packages/font-glyphs/src/letter/greek/phi.ptl
> +			local df : include : DivFrame para.diversityMM 3
Capital and non-split lower ef could stand to be adjusted though.

2024-12-09 17:09 UTC, jmcwilliams403 commented
Regarding `Ԕ`/`Ԗ`/`ԕ`/`ԗ`
`Ԕ`/`ԕ` are perfect already, while `Ԗ`/`ԗ` could stand be adjusted some other way besides simply making the whole character wider, because the `Х`/`х` parts are already too wide since they only use half of the x-shape.

2024-12-10 05:28 UTC, merged